### ISSUE TITLE
Detach repo from unmaintained original

### ISSUE THREAD

**Issue by rugk** [pimeys/apns2#9]
Can you please detach this repo from the not maintained fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by pimeys** [comment]
Ok, so my plan is definitely to make this the official apns2 library, I have contacted the original maintainer, got no response so here's my thoughts:

 - This is a complete rewrite, but started as a fork because we needed this-and-that which was not in the original library
 - I will release it in crates.io when the time comes
 - I will continue maintaining it, we use solely this version in our system
 - ... but right now this relies on a hyper version which is a branch from 0.11.18 and will be part of hyper 0.12, whenever @seanmonstar feels the code is good enough to merge
 - ... therefore I consider this library to be a test until we can use stable libraries as our base.

But you are right, I will detach this.

**Comment by pimeys** [comment]
Repo is detached now, everybody who forked this repo has still their fork to here.
